#!/bin/bash
a=4
b=10

if [ $a -gt $b ]    
then
      echo "a is greater than b"
elif [ $a -ge $b ]
then
      echo "a is greater than or equal to b"
elif [ $a -eq $b ]
then
      echo "a is equal to b"
else
      echo "a is smaller than b"
fi
